# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-14 17:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UrlQueueWatchModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('url_id', models.IntegerField()),
                ('status', models.CharField(max_length=255)),
                ('owner', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'url_queue_watch',
                'verbose_name': 'Url Queue Watch',
                'verbose_name_plural': 'Url Queue Watches',
            },
        ),
        migrations.CreateModel(
            name='UserDataStorageModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, editable=False, max_length=100, null=True)),
                ('updated_by', models.CharField(blank=True, editable=False, max_length=255, null=True)),
                ('url_link', models.URLField()),
                ('url_category', models.CharField(choices=[(b'genel', b'genel'), (b'sanat', b'sanat'), (b'askeri', b'askeri'), (b'oyun', b'oyun'), (b'bilim kurgu', b'bilim kurgu'), (b'muzik', b'muzik'), (b'gunluk yasam', b'gunluk yasam')], max_length=255)),
                ('url_desc', models.TextField()),
                ('url_time', models.IntegerField(null=True)),
                ('watch_count', models.IntegerField()),
                ('send_queue', models.CharField(choices=[(b'ACTIVE', b'ACTIVE'), (b'IN_QUEUE', b'IN_QUEUE'), (b'FINISHED', b'FINISHED')], max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_data_storage',
                'verbose_name': 'User Data Storage',
                'verbose_name_plural': 'User Data Storages',
            },
        ),
        migrations.CreateModel(
            name='UsersWatchedUrlModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_id', models.IntegerField()),
                ('url_id', models.IntegerField()),
            ],
            options={
                'db_table': 'users_watched_url',
                'verbose_name': 'users_watched_url',
                'verbose_name_plural': 'user_watched_urls',
            },
        ),
    ]
